In [1]:
import numpy as np

In [16]:
%%timeit
L =[]
for i in range(10000):
    L.append(i)

403 µs ± 60.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
%%timeit
Lnum = np.arange(10000)

3.67 µs ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
%%timeit
# to square every element of the list using only for loops
L =[]
for i in range(10000):
    L.append(i**2)

2.28 ms ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%%timeit
[i**2 for i in range(10000)]

1.98 ms ± 37.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%%timeit
l = np.arange(10000)
l2 = l**2

6.3 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
import random
import math

px = [random.gauss(0, 10) for i in range(100000)]
py = [random.gauss(0, 10) for i in range(100000)]

In [2]:
%%timeit

pt = []
for px_i, py_i in zip(px, py):
    pt.append(math.sqrt(px_i**2 + py_i**2))

23.1 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
import numpy as np

px = np.array(px)
py = np.array(py)
px, py

(array([-5.32934667, 18.72374772,  6.96034087, ..., -6.88514995,
        11.72751268, -5.08110035]),
 array([-5.78379212,  3.70989121, -2.01736772, ..., -0.79598757,
         8.70246878,  4.30970604]))

In [4]:
%%timeit

pt = np.sqrt(px**2 + py**2)

197 µs ± 3.27 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
import ROOT

Welcome to JupyROOT 6.28/04


In [6]:
ROOT.gInterpreter.Declare('''
void compute_pt(int32_t N, double* px, double* py, double* pt) {
    for (int32_t i = 0; i < N; i++) {
        pt[i] = sqrt(px[i]*px[i] + py[i]* py[i]);
    }
}
''')

True

In [7]:
pt = np.empty_like(px)
ROOT.compute_pt(len(px), px, py, pt)
pt

array([ 7.8647433 , 19.08774533,  7.24680051, ...,  6.93100902,
       14.60368161,  6.66266816])

In [8]:
%%timeit

ROOT.compute_pt(len(px), px, py, pt)

209 µs ± 5.39 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
import numba as nb

@nb.jit(nopython=True)
def compute_pt(px, py):
    pt = np.empty_like(px)
    for i, (px_i, py_i) in enumerate(zip(px, py)):
        pt[i] = np.sqrt(px_i**2 + py_i**2)
    return pt

In [14]:
compute_pt(px, py)

array([ 7.8647433 , 19.08774533,  7.24680051, ...,  6.93100902,
       14.60368161,  6.66266816])

In [15]:
%%timeit

compute_pt(px, py)

163 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
